# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/design_1_fpga1_top_0_2.xci
# IP: The module: 'design_1_fpga1_top_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/vio_0/vio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet

# IP: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_1/blk_mem_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_2/blk_mem_gen_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_2 || ORIG_REF_NAME==blk_mem_gen_2} -quiet] -quiet

# IP: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_3/blk_mem_gen_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_3 || ORIG_REF_NAME==blk_mem_gen_3} -quiet] -quiet

# IP: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_4/blk_mem_gen_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_4 || ORIG_REF_NAME==blk_mem_gen_4} -quiet] -quiet

# XDC: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/vio_0/vio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet

# XDC: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc

# XDC: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc

# XDC: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc

# XDC: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/nexy4_ddr.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fpga1_top_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/design_1_fpga1_top_0_2.xci
# IP: The module: 'design_1_fpga1_top_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/vio_0/vio_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet

# IP: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_1/blk_mem_gen_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_2/blk_mem_gen_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_2 || ORIG_REF_NAME==blk_mem_gen_2} -quiet] -quiet

# IP: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_3/blk_mem_gen_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_3 || ORIG_REF_NAME==blk_mem_gen_3} -quiet] -quiet

# IP: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_4/blk_mem_gen_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_4 || ORIG_REF_NAME==blk_mem_gen_4} -quiet] -quiet

# XDC: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/vio_0/vio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet

# XDC: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc

# XDC: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc

# XDC: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc

# XDC: c:/Users/dongxuen/fpga1+script/fpga_1_323/dm_server/demo_group.srcs/sources_1/bd/design_1/ip/design_1_fpga1_top_0_2/src/nexy4_ddr.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fpga1_top_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
